config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users

  resources :articles do
      resources :comments, only: [:create, :update, :destroy]
  end

  root 'articles#index'

  get "/dashboard", to: "welcome#dashboard"

  put "/articles/:id/publish", to: "articles#publish"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_article
  # before_action :authenticate_user!

  # POST /comments
  # POST /comments.json
  def create
    if user_signed_in?
      @comment = current_user.comments.new(comment_params)
    else
      anonimousUser = User.find(2)
      @comment = anonimousUser.comments.new(comment_params)
    end
    
    @comment.article = @article

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
        @article = Article.find(params[:article_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li>
	<!-- Inicia padre - nivel 0 -->
	<div class="comment-main-level">
		<!-- Avatar -->
		<!-- <div class="comment-avatar"><img src="<%= comment.user.avatar %>" alt=""></div> -->
		<!-- Contenedor del Comentario -->
		<div class="comment-box">
			<div class="comment-head">
				<% if @article.user_id == comment.user_id %>
					<h6 class="comment-name by-author"><%= comment.user.fullname %></h6>
				<% else %>
					<h6 class="comment-name"><%= comment.user.fullname %></h6>
				<% end %>
				<span>Hace <%= time_ago_in_words(comment.created_at) %></span>
				<i><%= link_to '', [@article, comment], class: 'fa fa-times fa-lg text-red' %></i>
			</div>
			<div class="comment-content">
				<%= comment.body %>
			</div>
		</div>
	</div>
	<!-- Fin Padre -->
</li>

app/views/comments/_form.html.erb
<div class="row">
    <div class="col-lg-4 col-lg-offset-4 col-xs-8 col-xs-offset-2">
        <%= form_for([@article, @comment], remote: true, html: { id: 'comments-form', :"data-type" => "json", class: 'form-horizontal' }) do |f| %>
            <% if @comment.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

                    <ul>
                    <% @comment.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="field form-group">
                <% f.label :body %><br>
                <%= f.text_area :body, class: 'form-control', rows: '3', placeholder: 'Escriba su comentario' %>
            </div>
            <div class="actions">
                <%= f.submit class: 'btn btn-default' %>
            </div>
        <% end %>
    </div>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>