config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users

  resources :articles do
      resources :comments, only: [:create, :update, :destroy]
  end

  root 'articles#index'

  get "/dashboard", to: "welcome#dashboard"

  put "/articles/:id/publish", to: "articles#publish"

end

app/models/article.rb
class Article < ActiveRecord::Base
    include AASM

    belongs_to :user
    has_many :comments
    has_many :has_categories, dependent: :destroy # 'dependent' para que se eliminen en cascada los registros en has_categories
    has_many :categories, through: :has_categories

    validates :title, presence: true, uniqueness: true
    validates :body, presence: true, length: { minimum: 20}
    before_create :set_visits_count
    # before_save :method
    # before_validation :method
    after_create :save_categories
    # after_create :send_mail
    # after_save :method
    # after_save :method on: :create

    has_attached_file :cover, styles: { medium: "1280x720", thumb: "800x600" }
    validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/

    # Metodo de clase para filtrar los articulos publicados
    # Podemos utilizar cualquiera de las dos formas
    scope :publicados, -> { where(state: "published") }
    # def self.publicados
    #     Article.where(state:"published")
    # end
    scope :ultimos, -> { order("created_at DESC") }


    # Custom Setter
    def categories=(value)
        @categories = value
    end

    def update_visits_count
        self.update(visits_count: self.visits_count + 1)
    end

    aasm column: "state" do
        state :in_draft, initial: true
        state :published

        event :publish do
            transitions from: :in_draft, to: :published
        end

        event :unpublish do
            transitions from: :published, to: :in_draft
        end
    end

    private

    def set_visits_count
        self.visits_count = 0
    end

    def save_categories
        unless @categories.nil?
            @categories.each do |category_id|
                HasCategory.create(category_id: category_id, article_id: self.id)
            end
        end
    end

    def send_mail
         ArticleMailer.new_article(self).deliver_later
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    # Controlando acciones con CallBacks
    # before_action :validate_user, except: [:show, :index]
    before_action :authenticate_user!, only: [:create, :new]
    # Con este otro eliminamos codigo repetido, DRY
    before_action :set_article, except: [:index, :new, :create]
    # Para otorgar permisos al usuario logeado de acuerdo a el campo permission_level
    before_action :authenticate_editor!, only: [:new, :create, :update]
    before_action :authenticate_admin!, only: [:destroy, :publish]

    # GET /articles
    def index
        # Variable de clase Vista y Controlador con todos los registros
        # pero ahora utilizando el filtro de los scopes declarados en el modelo
        # @articles = Article.publicados.ultimos
        # Ahora paginamos el resultado de los filtros anteriores
        @articles = Article.paginate(page: params[:page], per_page: 10).publicados.ultimos

    end
    # GET /articles/:id
    def show
        # Encontrar un registro por ID
        @article = Article.find(params[:id])
        # Esto es lo mismo que la linea anterior pero ahorrando codigo ya que se repetia en los demas metodos
        @article.update_visits_count

        @comment = Comment.new


        # Usando Where
        Article.where("id = ? OR title = ? ", params[:id], params[:title])
        # Porque NO usar interpolación de Cadenas, puede existir SQL Injection
        Article.where("id = #{params[:id]} ")
        # Diferente de
        Article.where.not("id = ? ", params[:id])
    end

    # GET /articles/new
    def new
        @article = Article.new
        @categories = Category.all
    end

    # POST /articles/:id/edit
    def edit
        # Encontrar un registro por ID
        @article = Article.find(params[:id])
    end

    # POST /articles
    def create
        # @article = Article.new(title: params[:article][:title], body: params[:article][:body])
        # Ahora lo mismo pero con StrongParams para indicar que campos son permitidos de tocar
        @article = current_user.articles.new(article_params)
        @article.categories = params[ :categories ]

        # Cualquiera de estas formas funciona para lo mismo
        # if @article.invalid?
        # if @article.valid?
        #     @article.save
        #     redirect_to @article
        # else
        #     render :new
        # end

        if @article.save
            redirect_to @article
        else
            render :new
        end

        # Bota un error para ver los parametros que le llegan al controlador desde el form
        # raise params.to_yaml
    end

    # PUT /articles/:id
    def update
        # Encontramos el Articulo a editar
        @article = Article.find(params[:id])

        # Se puede hacer con update o update_attributes
        # @article.update_attributes({title: 'Nuevo Titulo'})
        if @article.update(article_params)
            # Aplican las mismas reglas de StrongParams
            redirect_to @article
        else
            render :edit
        end

    end

    # DELETE /articles/:id
    def destroy
        @article = Article.find(params[:id])
        # Elimina el objeto de la BD
        @article.destroy

        redirect_to articles_path
    end

    def publish
        @article.publish!
        redirect_to @article
    end

    # Metodos privados
    private

    def set_article
        @article = Article.find(params[:id])
    end

    def validate_user
        redirect_to new_user_session_path, notice: "Necesita iniciar sesión!"
    end

    def article_params
        params.require(:article).permit(:title, :body, :cover, :categories, :markup_body)
    end

end

app/views/articles/_article.html.erb
<div class="row">
    <div class="post-preview">
        <div class="col-lg-4 col-sm-3 col-xs-3">
            <%= image_tag article.cover.url(:thumb), class: 'img-circle img-responsive center-block img-circle' %>
        </div>
        <div class="col-lg-8 col-sm-9 col-xs-9">
            <h2 class="post-title">
                <%= link_to article.title, article %>
            </h2>
            <h3 class="post-subtitle">
                <% truncate(article.body, length: 100) %>
            </h3>
            <p class="post-meta">Posted by <%= article.user.email %> on July 8, 2014</p>
        </div>
    </div>
</div>
<hr>

app/views/articles/_comments.html.erb
<div class="row">
    <div class="col-lg-12 text-center">
        <h4><strong>Participa en los commentarios</strong></h4>
        <br>
    </div>
</div>

<!-- Contenedor Principal -->
<div class="col-xs-8 comments-container">
    <ul id="comments-list" class="comments-list">

        <% if @article.comments.count > 0 %>

        <%= render @article.comments %>

        <% else %>
        <strong><em>Sin comentarios</em></strong>
        <% end %>

    </ul>
</div>

<div class="row">
    <div class="text-center">
        <%= render 'comments/form' %>
    </div>
</div>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1">

            <!-- Si no viene definida la Variable se define con un valor por default -->
            <% name ||= 'Crear' %>

            <br><br>
            <h1 class="text-center"><%= name %> Artículo</h1>
            <br><br>

            <%= form_for(@article, html: { id: "articles_form", class: 'form-horizontal' }) do |f| %>
                <% @article.errors.full_messages.each do |error| %>
                <div class="lmx-error top top-space">
                    * <%= error %>
                </div>
                <% end %>

                <div class="field form-group">
                    <!-- Se pueden utilizar las llaves {} o no RoR ya lo sabe -->
                    <%= f.label :title, 'Titulo:' %>
                    <%= f.text_field :title, {placeholder: 'Titulo', class: 'form-control'} %>
                </div>
                <div class="field form-group">
                    <label>Portada:</label>
                    <%= f.file_field :cover %>
                </div>

                <div class="field form-group">
                    <%= f.text_area :body, placeholder: 'Contenido del artículo', style: 'height:250px;', class: 'form-control', id: 'wysihtml5s' %>
                </div>

                <div class="field form-group">
                    <label>Categorias:</label>
                    <% @categories.each do |category| %>
                        <div class="field form-group">
                            <%= check_box_tag 'categories[]', category.id %> <%= category.name %>
                        </div>
                    <% end %>
                </div>
                <div class="field form-group">
                    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
                </div>
            <% end %>
        </div>
    </div>
</div>
<script>
    // wysihtml5 editor for body post
    $(document).ready(function(){

        $('#wysihtml5s').each(function(i, elem) {
            $(elem).wysihtml5();
        });

    })
</script>

app/views/articles/edit.html.erb
<div style="margin:0 auto; width:80%;">
    <!-- <h1>Editar Artículo</h1> -->
    <!-- Variables locales hacia el parcial -->
    <%= render 'form', name: 'Editar' %>
</div>

app/views/articles/index.html.erb
<%= render ('partials/index_front') %>

<!-- Controles par acrear artículos -->
<div class="container">
<div class="row">
    <br/>
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <% if user_signed_in? and (current_user.id == 1 or  current_user.id == 3) %>
        <%= link_to 'Crear Artículo', new_article_path, class: 'btn btn-warning' %>
        <%= link_to 'Dashboard', '/dashboard', class: 'btn btn-warning' %>
    <% end %>
    </div>
</div>
</div>
<hr>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12 col-xs-12">

            <!-- Haciendolo con un parcial, el estilo que contenga es aplicado a cada elemento de la colección -->
            <!-- El parcial debe llamarse como el recurso, en este caso espera un parcial llamado _article -->
            <!-- ya que la colección es 'articles' el recurso es 'article' -->
            <%= render @articles %>

            <!-- Pager -->
            <ul class="pager">
                <li class="next">
                    <!-- <a href="#">Older Posts &rarr;</a> -->
                </li>
            </ul>

        </div>
    </div>
</div>

<hr>

<div class="top-space text-center">
    <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<!-- <h1>Crear Artículo</h1> -->
<!-- No pasamos la Variable locales hacia el parcial -->
<%= render 'form' %>

app/views/articles/show.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url(<%= @article.cover.url %>)">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1><%= @article.title %></h1>
                    <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
                    <span class="meta">Posted by <a href="#">Start Bootstrap</a> on August 24, 2014</span>
                    <% unless @article.user.nil? %>
                        Escrito por: <%= @article.user.email %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-xs-6">
                <div class="text-left text-red">
                    <span><%= @article.visits_count %> visita(s) - <%= @article.comments.count %> comentario(s)</span>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="text-right">
                    <!-- Aquí se deben mostrar las categorias -->
                    <span class="btn glyphicon glyphicon-tags" aria-hidden="true"></span>
                    <% @article.categories.each do |category| %>
                        <%= link_to category.name, category, class: 'btn btn-default', style: "color: #{category.color}" %>
                    <% end %>
                </div>
            </div>
        </div>
        <hr>

        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-xs-10 col-xs-offset-1 postbody-text">
                <% Sanitize.fragment(@article.body, Sanitize::Config::RELAXED).html_safe %>
                <%= @article.body.html_safe %>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="text-left text-center">
                    &larr;
                    <%= link_to 'Atras', articles_path, class: 'btn btn-primary' %>
                </div>
            </div>
        </div>
        <hr>

        <div class="row">
            <%= render 'articles/comments' %>
        </div>
    </div>
</article>

<hr>